### ISSUE TITLE
Komponenty > Logo :onfocus (1.4.3)

### ISSUE THREAD

**Issue by athelas64** [slovensko-digital/navody.digital#611]
Logo návody.digital nemá požadovaný kontrast keď je zamerané (kontast 1.6:1, požadovaný 3:1

![logo_focus_povodna_farba](https://github.com/slovensko-digital/navody.digital/assets/2703018/a18c98c0-df3f-4117-a891-e06a7c0658c4)

Návrh riešenia:
```CSS
  sdn-header__link:focus {
  outline: 3px solid transparent;
  box-shadow: 0 -2px #ffbf47,0 4px #ffffff;  /*zmena farby podciarknutia na #ffffff */
  text-decoration: none;
  color: #06070b;
  background-color:#003FB7;  /*fejk modra z ktorej bude po inverte ta spravna zlta */
  filter:invert(1); /*invert farby loga*/
  padding: 3px;  /* keď sa ohraničenie dotýka priamo okraju písmena, zhoršuje to čitateľnosť, 2-3px je vhodný padding */
}
```
![logo_focus_opravena_farba](https://github.com/slovensko-digital/navody.digital/assets/2703018/321d2c64-7040-4a0b-bfe2-de9b045a75d3)
