### ISSUE TITLE
Komponenty > Tlačidlo Späť > focus je iný ako pri ostatných komponentoch (2.4.7)

### ISSUE THREAD

**Issue by athelas64** [slovensko-digital/navody.digital#618]
Tlačidlo Späť pri zameraní má miesto žltého podfarebenia len pásik, 
![2023-10-07_15h54_22](https://github.com/slovensko-digital/navody.digital/assets/2703018/1af6c120-0755-4249-ac4e-a27b20723912)

je to preto, že trieda govuk-back-link sa bije s button-back
`<button type="submit" class="govuk-back-link button-back vote-app-back">Späť</button>`

Navrhované riešenie:
vyhodiť z deklarácie button-back stavy focus, hover aj active 

![2023-10-07_15h55_11](https://github.com/slovensko-digital/navody.digital/assets/2703018/3c273e4a-cc9f-4673-bea1-dcc5b65c5054)

```CSS
.button-back
/*.button-back:hover,
.button-back:focus,
.button-back:active */ {
  border:none;
  background:none;
  padding:0 0 0 14px;
  cursor:pointer;
  outline:none
}
```
