### ISSUE TITLE
Komponenty > Footer newsletter > kontrast textu (1.4.3)

### ISSUE THREAD

**Issue by athelas64** [slovensko-digital/navody.digital#623]
Nápis novinky emailom (Raz mesačne) má opacity 0.6 a je potrebné ju zvýšiť na 0.8 tak, aby mal tento text dostatočný kontrast a zároveň sa to ujednotí s ostatným textom, ktorý má tiež 0.8 už teraz.
```CSS
.sdn-footer__newsletter-heading-tooltip {
    font-family: Roboto,arial,sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-weight: 400;
    font-size: 12px;
    font-size: .75rem;
    line-height: 1.25;
    opacity: .6  /* prepisat na opacity: .8 */
}
```
Pred:
![kontrast_povodne](https://github.com/slovensko-digital/navody.digital/assets/2703018/bec008c6-d818-46d2-83e7-c1eb157d69e2)
Po úprave:
![kontrast_opravene](https://github.com/slovensko-digital/navody.digital/assets/2703018/cc75001e-6701-40d9-99a5-ca17a20e6071)
